# Build
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/workflow-runner .
# Run
# docker run -i --rm -p 8080:8080 quarkus/workflow-runner
FROM registry.access.redhat.com/ubi8/openjdk-17:1.11

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

COPY --chown=185 target/*.jar /deployments/

EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/workflow-runner.jar"

