apiVersion: bindings.knative.dev/v1beta1
kind: KafkaBinding
metadata:
  name: kafka-binding-workflow-runner
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: workflow-runner
  bootstrapServers:
    - my-cluster-kafka-bootstrap:9092