---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-03-16 - 14:05:25 +0000
  labels:
    app.kubernetes.io/name: jitexecutor-bpmn
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: jitexecutor-bpmn
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: jitexecutor-bpmn
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-03-16 - 14:05:25 +0000
  labels:
    app.kubernetes.io/name: jitexecutor-bpmn
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: jitexecutor-bpmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jitexecutor-bpmn
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-03-16 - 14:05:25 +0000
      labels:
        app.kubernetes.io/name: jitexecutor-bpmn
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: ORG_KIE_DEPLOYMENT_PATH
              value: /deployments/data
          image: quay.io/dsalerno/jitexecutor-bpmn:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: jitexecutor-bpmn
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /deployments/data/applicantworkflow.sw.json
              name: input-sw
              subPath: applicantworkflow.sw.json
      volumes:
        - name: input-sw
          configMap:
            name: input-sw
